version: "3.7"

services:
  db:
    container_name: micro_service_db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/data
      - ./db/extensions:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5433:${DATABASE_PORT}"

networks:
  backend:

volumes:
  db-data:
